### ISSUE TITLE
Automatically determine the HTTPSE version to use from latest XPI

### ISSUE THREAD

**Issue by bbondy** [brave/https-everywhere-builder#7]
We can use this link:
https://www.eff.org/files/https-everywhere-latest.xpi

Then extract the xpi file as a zip.

Then parse the `manifest.json` file for the version.

Then always use that dynamically.

This will ensure anytime we build our component, it will always have the latest rules.

**Comment by cschanaj** [comment]
IMHO, it would be even better if you could utilize the update channel EFF is providing, in order to access the latest rules. The signed rulesets are available at https://www.https-rulesets.org/v1/ and the documentations are [here](https://github.com/EFForg/https-everywhere/blob/ffcd66a47b8eb07500b154cd251aef9053e4b076/docs/en_US/ruleset-update-channels.md). Though it might require additional effort to incorporate this into the existing code.

**Comment by cschanaj** [comment]
I have submitted a PR on https://github.com/brave/https-everywhere-builder/issues/7#issuecomment-419297664 with #12 to always build HTTPSE with the latest rulesets
